package model;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 12 11:17:30 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for LoginView1.
     * @return LoginView1
     */
    public ViewObjectImpl getLoginView1() {
        return (ViewObjectImpl) findViewObject("LoginView1");
    }
    
    public void doLogin(String username, String password) {

        ViewObject vo = findViewObject("LoginView1");

        vo.defineNamedWhereClauseParam("username",null,null);
        vo.setNamedWhereClauseParam("username", username);

        vo.defineNamedWhereClauseParam("password",null,null);
        vo.setNamedWhereClauseParam("password", password);

        vo.setWhereClause("USERNAME like :username AND PASSWORD like :password");
        vo.executeQuery();

        if(vo.first() == null || vo.first().equals(false)) {
            throw new JboException("Username or Password uncorrect");
        }
    }
    
    public void doRegistration(String username, String password) {
            
        ViewObject vo = findViewObject("LoginView1");
        Row row = vo.createRow();
        // USER OR PASSWORD ARE BLANK
        if (username.trim().equals("") || password.trim().equals("")) {
            throw new JboException("Username or Password not valid");
        }
        // USER EXISTS YET
        if (!username.trim().equals("")) {
            ViewObject vo2 = findViewObject("LoginView1");

            vo2.defineNamedWhereClauseParam("user",null,null);
            vo2.setNamedWhereClauseParam("user", username);

            vo2.setWhereClause("USERNAME like :user");
            vo2.executeQuery();

            if(!vo2.first() == null || vo2.first().equals(true)) {
                throw new JboException("This user exists yet");
            }
        }
        row.setAttribute("Username", username);
        row.setAttribute("Password", password);
        vo.insertRow(row);
        getDBTransaction().commit();
    }
}

