package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 12 11:28:40 CEST 2023
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void doLogin(String username, String password);

    void doRegistration(String username, String password);
}

